#! /bin/sh

$HOME/.config/polybar/launch.sh &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config swallow_first_click true

bspc config pointer_modifier mod
bspc config pointer_action1 resize_side
bspc config pointer_action3 move

bspc config normal_border_color "#2f343f"
bspc config active_border_color "#2f343f"
bspc config focused_border_color "#5294e2"

bspc rule -a Emacs state=tiled
bspc rule -a Surf desktop='^2' state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
